//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coolgym_webapi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class coolgym_webapi_Contexts_Rentals_Interfaces_REST_RentalRequestsController_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal coolgym_webapi_Contexts_Rentals_Interfaces_REST_RentalRequestsController_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("coolgym-webapi.Resources.coolgym_webapi.Contexts.Rentals.Interfaces.REST.RentalRe" +
                            "questsController.en", typeof(coolgym_webapi_Contexts_Rentals_Interfaces_REST_RentalRequestsController_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication required..
        /// </summary>
        internal static string AuthenticationRequired {
            get {
                return ResourceManager.GetString("AuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while approving the rental request..
        /// </summary>
        internal static string ErrorApprovingRentalRequest {
            get {
                return ResourceManager.GetString("ErrorApprovingRentalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the rental request..
        /// </summary>
        internal static string ErrorCreatingRentalRequest {
            get {
                return ResourceManager.GetString("ErrorCreatingRentalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the rental request..
        /// </summary>
        internal static string ErrorUpdatingRentalRequest {
            get {
                return ResourceManager.GetString("ErrorUpdatingRentalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rental request operation could not be completed..
        /// </summary>
        internal static string GenericRentalOperationFailure {
            get {
                return ResourceManager.GetString("GenericRentalOperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string InvalidRentalOperation {
            get {
                return ResourceManager.GetString("InvalidRentalOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rental request status is invalid..
        /// </summary>
        internal static string InvalidRentalStatus {
            get {
                return ResourceManager.GetString("InvalidRentalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only clients can create rental requests..
        /// </summary>
        internal static string OnlyClientsCanCreateRentalRequests {
            get {
                return ResourceManager.GetString("OnlyClientsCanCreateRentalRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only pending rental requests can be approved..
        /// </summary>
        internal static string OnlyPendingRequestsCanBeApproved {
            get {
                return ResourceManager.GetString("OnlyPendingRequestsCanBeApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only providers can approve rental requests..
        /// </summary>
        internal static string OnlyProvidersCanApproveRentalRequests {
            get {
                return ResourceManager.GetString("OnlyProvidersCanApproveRentalRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only providers can update rental request status..
        /// </summary>
        internal static string OnlyProvidersCanUpdateRentalRequestStatus {
            get {
                return ResourceManager.GetString("OnlyProvidersCanUpdateRentalRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental request with id {0} was not found..
        /// </summary>
        internal static string RentalRequestNotFound {
            get {
                return ResourceManager.GetString("RentalRequestNotFound", resourceCulture);
            }
        }
    }
}
