//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coolgym_webapi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class coolgym_webapi_Contexts_BillingInvoices_Interfaces_REST_BillingInvoicesController_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal coolgym_webapi_Contexts_BillingInvoices_Interfaces_REST_BillingInvoicesController_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("coolgym_webapi.Resources.coolgym_webapi.Contexts.BillingInvoices.Interfaces.REST." +
                            "BillingInvoicesController.es", typeof(coolgym_webapi_Contexts_BillingInvoices_Interfaces_REST_BillingInvoicesController_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo con id {0} no fue encontrado..
        /// </summary>
        internal static string Equipment_with_id__0__was_not_found_ {
            get {
                return ResourceManager.GetString("Equipment with id {0} was not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de fecha inválido. Use yyyy-MM-dd..
        /// </summary>
        internal static string Invalid_date_format__Use_yyyy_MM_dd_ {
            get {
                return ResourceManager.GetString("Invalid date format. Use yyyy-MM-dd.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La factura con ID {0} no fue encontrada..
        /// </summary>
        internal static string Invoice_with_ID__0__was_not_found_ {
            get {
                return ResourceManager.GetString("Invoice with ID {0} was not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud de mantenimiento con id {0} no fue encontrada..
        /// </summary>
        internal static string Maintenance_request_with_id__0__was_not_found_ {
            get {
                return ResourceManager.GetString("Maintenance request with id {0} was not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo las solicitudes de mantenimiento completadas pueden generar facturas..
        /// </summary>
        internal static string Only_completed_maintenance_requests_can_generate_invoices_ {
            get {
                return ResourceManager.GetString("Only completed maintenance requests can generate invoices.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El identificador de usuario debe ser un número positivo..
        /// </summary>
        internal static string User_ID_must_be_positive_ {
            get {
                return ResourceManager.GetString("User ID must be positive.", resourceCulture);
            }
        }
    }
}
