//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coolgym_webapi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class coolgym_webapi_Contexts_Equipments_Interfaces_REST_EquipmentsController_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal coolgym_webapi_Contexts_Equipments_Interfaces_REST_EquipmentsController_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(("coolgym-webapi.Resources.coolgym_webapi.Contexts.Equipments.Interfaces.REST.Equip" +
                            "mentsController.en"), typeof(coolgym_webapi_Contexts_Equipments_Interfaces_REST_EquipmentsController_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the equipment.
        /// </summary>
        internal static string An_error_occurred_while_creating_the_equipment {
            get {
                return ResourceManager.GetString("An error occurred while creating the equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the equipment.
        /// </summary>
        internal static string An_error_occurred_while_deleting_the_equipment {
            get {
                return ResourceManager.GetString("An error occurred while deleting the equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the equipment.
        /// </summary>
        internal static string An_error_occurred_while_updating_the_equipment {
            get {
                return ResourceManager.GetString("An error occurred while updating the equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current level ({0}) must be between {1} and {2}..
        /// </summary>
        internal static string ControlCurrentLevelOutOfRange {
            get {
                return ResourceManager.GetString("ControlCurrentLevelOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum level ({0}) must be greater than minimum level ({1})..
        /// </summary>
        internal static string ControlInvalidRange {
            get {
                return ResourceManager.GetString("ControlInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum level cannot be negative. Value: {0}.
        /// </summary>
        internal static string ControlNegativeMinLevel {
            get {
                return ResourceManager.GetString("ControlNegativeMinLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power status cannot be empty..
        /// </summary>
        internal static string ControlPowerEmpty {
            get {
                return ResourceManager.GetString("ControlPowerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set level ({0}) must be between {1} and {2}..
        /// </summary>
        internal static string ControlSetLevelOutOfRange {
            get {
                return ResourceManager.GetString("ControlSetLevelOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control status cannot be empty..
        /// </summary>
        internal static string ControlStatusEmpty {
            get {
                return ResourceManager.GetString("ControlStatusEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment with serial number &apos;{0}&apos; already exists..
        /// </summary>
        internal static string DuplicateSerialNumber {
            get {
                return ResourceManager.GetString("DuplicateSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment with id {0} not found.
        /// </summary>
        internal static string Equipment_with_id__0__not_found {
            get {
                return ResourceManager.GetString("Equipment with id {0} not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete equipment &apos;{0}&apos; because it is under maintenance..
        /// </summary>
        internal static string EquipmentInMaintenance {
            get {
                return ResourceManager.GetString("EquipmentInMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment with id {0} not found..
        /// </summary>
        internal static string EquipmentNotFound {
            get {
                return ResourceManager.GetString("EquipmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete equipment &apos;{0}&apos; because it is powered on. Please turn it off first..
        /// </summary>
        internal static string EquipmentPoweredOn {
            get {
                return ResourceManager.GetString("EquipmentPoweredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data provided..
        /// </summary>
        internal static string GenericValidationFailure {
            get {
                return ResourceManager.GetString("GenericValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidStatus {
            get {
                return ResourceManager.GetString("InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location address cannot be empty..
        /// </summary>
        internal static string LocationAddressEmpty {
            get {
                return ResourceManager.GetString("LocationAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location address cannot exceed 200 characters. Current length: {0}.
        /// </summary>
        internal static string LocationAddressTooLong {
            get {
                return ResourceManager.GetString("LocationAddressTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name cannot be empty..
        /// </summary>
        internal static string LocationNameEmpty {
            get {
                return ResourceManager.GetString("LocationNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name cannot exceed 100 characters. Current length: {0}.
        /// </summary>
        internal static string LocationNameTooLong {
            get {
                return ResourceManager.GetString("LocationNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories cannot be negative. Value: {0}.
        /// </summary>
        internal static string UsageNegativeCalories {
            get {
                return ResourceManager.GetString("UsageNegativeCalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today minutes ({0}) cannot exceed total minutes ({1})..
        /// </summary>
        internal static string UsageTodayExceedsTotal {
            get {
                return ResourceManager.GetString("UsageTodayExceedsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today minutes cannot be negative. Value: {0}.
        /// </summary>
        internal static string UsageTodayMinutesNegative {
            get {
                return ResourceManager.GetString("UsageTodayMinutesNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total minutes cannot be negative. Value: {0}.
        /// </summary>
        internal static string UsageTotalMinutesNegative {
            get {
                return ResourceManager.GetString("UsageTotalMinutesNegative", resourceCulture);
            }
        }
    }
}
