//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coolgym_webapi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class coolgym_webapi_Contexts_maintenance_Interfaces_REST_MaintenanceRequestsController_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal coolgym_webapi_Contexts_maintenance_Interfaces_REST_MaintenanceRequestsController_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("coolgym_webapi.Resources.coolgym_webapi.Contexts.maintenance.Interfaces.REST.Main" +
                            "tenanceRequestsController.es", typeof(coolgym_webapi_Contexts_maintenance_Interfaces_REST_MaintenanceRequestsController_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al crear la solicitud de mantenimiento..
        /// </summary>
        internal static string An_error_occurred_while_creating_the_maintenance_request_ {
            get {
                return ResourceManager.GetString("An error occurred while creating the maintenance request.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al eliminar la solicitud de mantenimiento..
        /// </summary>
        internal static string An_error_occurred_while_deleting_the_maintenance_request_ {
            get {
                return ResourceManager.GetString("An error occurred while deleting the maintenance request.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al actualizar la solicitud de mantenimiento..
        /// </summary>
        internal static string An_error_occurred_while_updating_the_maintenance_request_ {
            get {
                return ResourceManager.GetString("An error occurred while updating the maintenance request.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró una solicitud de mantenimiento con id {0}..
        /// </summary>
        internal static string Maintenance_request_with_id__0__was_not_found_ {
            get {
                return ResourceManager.GetString("Maintenance request with id {0} was not found.", resourceCulture);
            }
        }
    }
}
