//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coolgym_webapi.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class coolgym_webapi_Contexts_ClientPlans_Interfaces_REST_ClientPlansController_en {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal coolgym_webapi_Contexts_ClientPlans_Interfaces_REST_ClientPlansController_en() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(("coolgym-webapi.Resources.coolgym_webapi.Contexts.ClientPlans.Interfaces.REST.Clie" +
                            "ntPlansController.en"), typeof(coolgym_webapi_Contexts_ClientPlans_Interfaces_REST_ClientPlansController_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string Plan_Basic_Name {
            get {
                return ResourceManager.GetString("Plan.Basic.Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Perfect for individual users. Access to up to 6 machines..
        /// </summary>
        internal static string Plan_Basic_Description {
            get {
                return ResourceManager.GetString("Plan.Basic.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Plan_Standard_Name {
            get {
                return ResourceManager.GetString("Plan.Standard.Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to For active users. Access to up to 12 machines with maintenance support..
        /// </summary>
        internal static string Plan_Standard_Description {
            get {
                return ResourceManager.GetString("Plan.Standard.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        internal static string Plan_Premium_Name {
            get {
                return ResourceManager.GetString("Plan.Premium.Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to For power users. Access to up to 24 machines with full support..
        /// </summary>
        internal static string Plan_Premium_Description {
            get {
                return ResourceManager.GetString("Plan.Premium.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Small Company.
        /// </summary>
        internal static string Plan_Small_Company_Name {
            get {
                return ResourceManager.GetString("Plan.Small Company.Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Perfect for small businesses. Manage up to 10 clients..
        /// </summary>
        internal static string Plan_Small_Company_Description {
            get {
                return ResourceManager.GetString("Plan.Small Company.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Medium Company.
        /// </summary>
        internal static string Plan_Medium_Company_Name {
            get {
                return ResourceManager.GetString("Plan.Medium Company.Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ideal for growing companies. Manage up to 30 clients with maintenance support..
        /// </summary>
        internal static string Plan_Medium_Company_Description {
            get {
                return ResourceManager.GetString("Plan.Medium Company.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enterprise Premium.
        /// </summary>
        internal static string Plan_Enterprise_Premium_Name {
            get {
                return ResourceManager.GetString("Plan.Enterprise Premium.Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ultimate solution for large enterprises. Unlimited clients with priority support..
        /// </summary>
        internal static string Plan_Enterprise_Premium_Description {
            get {
                return ResourceManager.GetString("Plan.Enterprise Premium.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client plan with ID {0} not found..
        /// </summary>
        internal static string ClientPlanNotFound {
            get {
                return ResourceManager.GetString("ClientPlanNotFound", resourceCulture);
            }
        }
    }
}
