//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coolgym_webapi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class coolgym_webapi_Contexts_Equipments_Interfaces_REST_EquipmentsController_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal coolgym_webapi_Contexts_Equipments_Interfaces_REST_EquipmentsController_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(("coolgym-webapi.Resources.coolgym_webapi.Contexts.Equipments.Interfaces.REST.Equip" +
                            "mentsController.es"), typeof(coolgym_webapi_Contexts_Equipments_Interfaces_REST_EquipmentsController_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al registrar el equipo.
        /// </summary>
        internal static string An_error_occurred_while_creating_the_equipment {
            get {
                return ResourceManager.GetString("An error occurred while creating the equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al eliminar el equipo.
        /// </summary>
        internal static string An_error_occurred_while_deleting_the_equipment {
            get {
                return ResourceManager.GetString("An error occurred while deleting the equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al actualizar el equipo.
        /// </summary>
        internal static string An_error_occurred_while_updating_the_equipment {
            get {
                return ResourceManager.GetString("An error occurred while updating the equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nivel actual ({0}) debe estar entre {1} y {2}..
        /// </summary>
        internal static string ControlCurrentLevelOutOfRange {
            get {
                return ResourceManager.GetString("ControlCurrentLevelOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nivel máximo ({0}) debe ser mayor que el nivel mínimo ({1})..
        /// </summary>
        internal static string ControlInvalidRange {
            get {
                return ResourceManager.GetString("ControlInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nivel mínimo no puede ser negativo. Valor: {0}.
        /// </summary>
        internal static string ControlNegativeMinLevel {
            get {
                return ResourceManager.GetString("ControlNegativeMinLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado de energía no puede estar vacío..
        /// </summary>
        internal static string ControlPowerEmpty {
            get {
                return ResourceManager.GetString("ControlPowerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nivel a establecer ({0}) debe estar entre {1} y {2}..
        /// </summary>
        internal static string ControlSetLevelOutOfRange {
            get {
                return ResourceManager.GetString("ControlSetLevelOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado de control no puede estar vacío..
        /// </summary>
        internal static string ControlStatusEmpty {
            get {
                return ResourceManager.GetString("ControlStatusEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un equipo con el número de serie &apos;{0}&apos;..
        /// </summary>
        internal static string DuplicateSerialNumber {
            get {
                return ResourceManager.GetString("DuplicateSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo con id {0} no encontrado.
        /// </summary>
        internal static string Equipment_with_id__0__not_found {
            get {
                return ResourceManager.GetString("Equipment with id {0} not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el equipo &apos;{0}&apos; porque está en mantenimiento..
        /// </summary>
        internal static string EquipmentInMaintenance {
            get {
                return ResourceManager.GetString("EquipmentInMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo con id {0} no fue encontrado..
        /// </summary>
        internal static string EquipmentNotFound {
            get {
                return ResourceManager.GetString("EquipmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el equipo &apos;{0}&apos; porque está encendido. Por favor, apáguelo primero..
        /// </summary>
        internal static string EquipmentPoweredOn {
            get {
                return ResourceManager.GetString("EquipmentPoweredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de entrada inválidos..
        /// </summary>
        internal static string GenericValidationFailure {
            get {
                return ResourceManager.GetString("GenericValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado &apos;{0}&apos; no es válido..
        /// </summary>
        internal static string InvalidStatus {
            get {
                return ResourceManager.GetString("InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección de la ubicación no puede estar vacía..
        /// </summary>
        internal static string LocationAddressEmpty {
            get {
                return ResourceManager.GetString("LocationAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección de la ubicación no puede exceder los 200 caracteres. Longitud actual: {0}.
        /// </summary>
        internal static string LocationAddressTooLong {
            get {
                return ResourceManager.GetString("LocationAddressTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la ubicación no puede estar vacío..
        /// </summary>
        internal static string LocationNameEmpty {
            get {
                return ResourceManager.GetString("LocationNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la ubicación no puede exceder los 100 caracteres. Longitud actual: {0}.
        /// </summary>
        internal static string LocationNameTooLong {
            get {
                return ResourceManager.GetString("LocationNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las calorías no pueden ser negativas. Valor: {0}.
        /// </summary>
        internal static string UsageNegativeCalories {
            get {
                return ResourceManager.GetString("UsageNegativeCalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los minutos de hoy ({0}) no pueden exceder los minutos totales ({1})..
        /// </summary>
        internal static string UsageTodayExceedsTotal {
            get {
                return ResourceManager.GetString("UsageTodayExceedsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los minutos de hoy no pueden ser negativos. Valor: {0}.
        /// </summary>
        internal static string UsageTodayMinutesNegative {
            get {
                return ResourceManager.GetString("UsageTodayMinutesNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los minutos totales no pueden ser negativos. Valor: {0}.
        /// </summary>
        internal static string UsageTotalMinutesNegative {
            get {
                return ResourceManager.GetString("UsageTotalMinutesNegative", resourceCulture);
            }
        }
    }
}
