//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coolgym_webapi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class coolgym_webapi_Contexts_Rentals_Interfaces_REST_RentalRequestsController_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal coolgym_webapi_Contexts_Rentals_Interfaces_REST_RentalRequestsController_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(("coolgym-webapi.Resources.coolgym_webapi.Contexts.Rentals.Interfaces.REST.RentalRe" +
                            "questsController.es"), typeof(coolgym_webapi_Contexts_Rentals_Interfaces_REST_RentalRequestsController_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticación requerida..
        /// </summary>
        internal static string AuthenticationRequired {
            get {
                return ResourceManager.GetString("AuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al aprobar la solicitud de alquiler..
        /// </summary>
        internal static string ErrorApprovingRentalRequest {
            get {
                return ResourceManager.GetString("ErrorApprovingRentalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al crear la solicitud de alquiler..
        /// </summary>
        internal static string ErrorCreatingRentalRequest {
            get {
                return ResourceManager.GetString("ErrorCreatingRentalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al actualizar la solicitud de alquiler..
        /// </summary>
        internal static string ErrorUpdatingRentalRequest {
            get {
                return ResourceManager.GetString("ErrorUpdatingRentalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo completar la operación sobre la solicitud de alquiler..
        /// </summary>
        internal static string GenericRentalOperationFailure {
            get {
                return ResourceManager.GetString("GenericRentalOperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string InvalidRentalOperation {
            get {
                return ResourceManager.GetString("InvalidRentalOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado de la solicitud de alquiler no es válido..
        /// </summary>
        internal static string InvalidRentalStatus {
            get {
                return ResourceManager.GetString("InvalidRentalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo los clientes pueden crear solicitudes de alquiler..
        /// </summary>
        internal static string OnlyClientsCanCreateRentalRequests {
            get {
                return ResourceManager.GetString("OnlyClientsCanCreateRentalRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo se pueden aprobar solicitudes de alquiler en estado pendiente..
        /// </summary>
        internal static string OnlyPendingRequestsCanBeApproved {
            get {
                return ResourceManager.GetString("OnlyPendingRequestsCanBeApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo los proveedores pueden aprobar las solicitudes de alquiler..
        /// </summary>
        internal static string OnlyProvidersCanApproveRentalRequests {
            get {
                return ResourceManager.GetString("OnlyProvidersCanApproveRentalRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo los proveedores pueden actualizar el estado de las solicitudes de alquiler..
        /// </summary>
        internal static string OnlyProvidersCanUpdateRentalRequestStatus {
            get {
                return ResourceManager.GetString("OnlyProvidersCanUpdateRentalRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró una solicitud de alquiler con id {0}..
        /// </summary>
        internal static string RentalRequestNotFound {
            get {
                return ResourceManager.GetString("RentalRequestNotFound", resourceCulture);
            }
        }
    }
}
