// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coolgym_webapi.Contexts.Shared.Infrastructure.Persistence.Configuration;

#nullable disable

namespace coolgym_webapi.Migrations
{
    [DbContext(typeof(CoolgymContext))]
    partial class CoolgymContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("coolgym_webapi.Contexts.BillingInvoices.Domain.Model.Entities.BillingInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CompanyName");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedDate");

                    b.Property<int>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("IssuedAt");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime")
                        .HasColumnName("PaidAt");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedDate");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("IssuedAt");

                    b.HasIndex("UserId");

                    b.ToTable("billing_invoices", (string)null);
                });

            modelBuilder.Entity("coolgym_webapi.Contexts.Equipments.Domain.Model.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ActiveStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("active_status");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("installation_date");

                    b.Property<int>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPoweredOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_powered_on");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notes");

                    b.Property<int>("PowerWatts")
                        .HasColumnType("int")
                        .HasColumnName("power_watts");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_equipments_serial_number");

                    b.ToTable("equipments", (string)null);
                });

            modelBuilder.Entity("coolgym_webapi.Contexts.RentalCatalog.Domain.Model.Entities.RentalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_available");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Model")
                        .IsUnique();

                    b.ToTable("rental_items", (string)null);
                });

            modelBuilder.Entity("coolgym_webapi.Contexts.BillingInvoices.Domain.Model.Entities.BillingInvoice", b =>
                {
                    b.OwnsOne("coolgym_webapi.Contexts.BillingInvoices.Domain.Model.ValueObjects.InvoiceStatus", "Status", b1 =>
                        {
                            b1.Property<int>("BillingInvoiceId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("Status");

                            b1.HasKey("BillingInvoiceId");

                            b1.ToTable("billing_invoices");

                            b1.WithOwner()
                                .HasForeignKey("BillingInvoiceId");
                        });

                    b.OwnsOne("coolgym_webapi.Contexts.BillingInvoices.Domain.Model.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("BillingInvoiceId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("BillingInvoiceId");

                            b1.ToTable("billing_invoices");

                            b1.WithOwner()
                                .HasForeignKey("BillingInvoiceId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("coolgym_webapi.Contexts.Equipments.Domain.Model.Entities.Equipment", b =>
                {
                    b.OwnsOne("coolgym_webapi.Contexts.Equipments.Domain.Model.ValueObjects.ControlSettings", "Controls", b1 =>
                        {
                            b1.Property<int>("EquipmentId")
                                .HasColumnType("int");

                            b1.Property<int>("CurrentLevel")
                                .HasColumnType("int")
                                .HasColumnName("control_current_level");

                            b1.Property<int>("MaxLevelRange")
                                .HasColumnType("int")
                                .HasColumnName("control_max_level_range");

                            b1.Property<int>("MinLevelRange")
                                .HasColumnType("int")
                                .HasColumnName("control_min_level_range");

                            b1.Property<string>("Power")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("control_power");

                            b1.Property<int>("SetLevel")
                                .HasColumnType("int")
                                .HasColumnName("control_set_level");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("control_status");

                            b1.HasKey("EquipmentId");

                            b1.ToTable("equipments");

                            b1.WithOwner()
                                .HasForeignKey("EquipmentId");
                        });

                    b.OwnsOne("coolgym_webapi.Contexts.Equipments.Domain.Model.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<int>("EquipmentId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("location_address");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("location_name");

                            b1.HasKey("EquipmentId");

                            b1.ToTable("equipments");

                            b1.WithOwner()
                                .HasForeignKey("EquipmentId");
                        });

                    b.OwnsOne("coolgym_webapi.Contexts.Equipments.Domain.Model.ValueObjects.MaintenanceInfo", "MaintenanceInfo", b1 =>
                        {
                            b1.Property<int>("EquipmentId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("LastMaintenanceDate")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("maintenance_last_date");

                            b1.Property<DateTime?>("NextMaintenanceDate")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("maintenance_next_date");

                            b1.HasKey("EquipmentId");

                            b1.ToTable("equipments");

                            b1.WithOwner()
                                .HasForeignKey("EquipmentId");
                        });

                    b.OwnsOne("coolgym_webapi.Contexts.Equipments.Domain.Model.ValueObjects.UsageStats", "Usage", b1 =>
                        {
                            b1.Property<int>("EquipmentId")
                                .HasColumnType("int");

                            b1.Property<int>("CaloriesToday")
                                .HasColumnType("int")
                                .HasColumnName("usage_calories_today");

                            b1.Property<int>("TodayMinutes")
                                .HasColumnType("int")
                                .HasColumnName("usage_today_minutes");

                            b1.Property<int>("TotalMinutes")
                                .HasColumnType("int")
                                .HasColumnName("usage_total_minutes");

                            b1.HasKey("EquipmentId");

                            b1.ToTable("equipments");

                            b1.WithOwner()
                                .HasForeignKey("EquipmentId");
                        });

                    b.Navigation("Controls")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("MaintenanceInfo")
                        .IsRequired();

                    b.Navigation("Usage")
                        .IsRequired();
                });

            modelBuilder.Entity("coolgym_webapi.Contexts.RentalCatalog.Domain.Model.Entities.RentalItem", b =>
                {
                    b.OwnsOne("coolgym_webapi.Contexts.RentalCatalog.Domain.Model.ValueObjects.Money", "MonthlyPrice", b1 =>
                        {
                            b1.Property<int>("RentalItemId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("monthly_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("monthly_price_currency");

                            b1.HasKey("RentalItemId");

                            b1.ToTable("rental_items");

                            b1.WithOwner()
                                .HasForeignKey("RentalItemId");
                        });

                    b.Navigation("MonthlyPrice")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
